# Generated by Django 4.1.7 on 2023-04-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_user',
            new_name='is_active',
        ),
    ]
