# Generated by Django 4.1.7 on 2023-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('FA', 'Fantastyka'), ('HI', 'Historyczne'), ('KT', 'Kryminał i Thriller'), ('LE', 'Lektura'), ('RB', 'Reportaż i Biografia'), ('RO', 'Romans'), ('SF', 'Sci-Fi')], max_length=100),
        ),
    ]
