# Generated by Django 4.1.7 on 2023-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
