# Generated by Django 4.1.7 on 2023-04-05 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description_book_pages_alter_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
