# Generated by Django 4.1.7 on 2023-04-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
